[0m22:55:24.419945 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x731a04780b00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x731a04782d80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x731a04782db0>]}


============================== 22:55:24.423081 | 0de3223f-9384-4dd4-a9b8-d811145667ff ==============================
[0m22:55:24.423081 [info ] [MainThread]: Running with dbt=1.8.2
[0m22:55:24.423707 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/cyril/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:55:24.431236 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/cyril/.dbt')}
[0m22:55:24.431728 [info ] [MainThread]: Creating dbt configuration folder at 
[0m22:55:52.480821 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7392bc37af90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7392bf6919d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7392bc3a10d0>]}


============================== 22:55:52.483934 | 568d115a-3489-4d28-b60c-0200b7512c9c ==============================
[0m22:55:52.483934 [info ] [MainThread]: Running with dbt=1.8.2
[0m22:55:52.484558 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/cyril/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m22:55:58.459938 [debug] [MainThread]: Starter project path: /home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/include/starter_project
[0m22:55:58.463228 [info ] [MainThread]: 
Your new dbt project "dbt_for_redshift" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:55:58.463749 [info ] [MainThread]: Setting up your profile.
[0m22:56:05.503078 [debug] [MainThread]: Redshift adapter: Setting redshift_connector to ERROR
[0m22:56:05.503797 [debug] [MainThread]: Redshift adapter: Setting redshift_connector.core to ERROR
[0m00:52:12.053663 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x788aced5aba0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x788aceb26120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x788acd3013d0>]}


============================== 00:52:12.056807 | 784a3dc4-ce01-4075-9019-4dab54658c1b ==============================
[0m00:52:12.056807 [info ] [MainThread]: Running with dbt=1.8.2
[0m00:52:12.057453 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/cyril/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m00:52:33.096212 [debug] [MainThread]: Starter project path: /home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/include/starter_project
[0m00:52:33.099985 [info ] [MainThread]: 
Your new dbt project "dbt_for_redshift" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:52:33.100448 [info ] [MainThread]: Setting up your profile.
[0m00:52:35.981033 [debug] [MainThread]: Redshift adapter: Setting redshift_connector to ERROR
[0m00:52:35.981690 [debug] [MainThread]: Redshift adapter: Setting redshift_connector.core to ERROR
[0m00:57:04.484312 [info ] [MainThread]: Profile dbt_for_redshift written to /home/cyril/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:57:04.487410 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 292.49164, "process_user_time": 1.39539, "process_kernel_time": 0.176049, "process_mem_max_rss": "98732", "process_in_blocks": "40", "process_out_blocks": "88"}
[0m00:57:04.489033 [debug] [MainThread]: Command `dbt init` succeeded at 00:57:04.488780 after 292.49 seconds
[0m00:57:04.490165 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x788acd1952b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x788acc5b0710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x788acca99820>]}
[0m00:57:04.491337 [debug] [MainThread]: Flushing usage events
[0m00:58:18.051854 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a1029e68650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a102c1c0a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a1029e6a3f0>]}


============================== 00:58:18.055019 | 005f14a4-4e12-424d-8edf-23e3cf128d4c ==============================
[0m00:58:18.055019 [info ] [MainThread]: Running with dbt=1.8.2
[0m00:58:18.055634 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/cyril/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:58:18.064319 [info ] [MainThread]: dbt version: 1.8.2
[0m00:58:18.064835 [info ] [MainThread]: python version: 3.12.3
[0m00:58:18.065239 [info ] [MainThread]: python path: /home/cyril/Documents/vscode_project/dbt_aws/.venv/bin/python
[0m00:58:18.065661 [info ] [MainThread]: os info: Linux-6.8.0-35-generic-x86_64-with-glibc2.39
[0m00:58:18.212094 [debug] [MainThread]: Redshift adapter: Setting redshift_connector to ERROR
[0m00:58:18.212759 [debug] [MainThread]: Redshift adapter: Setting redshift_connector.core to ERROR
[0m00:58:18.268804 [info ] [MainThread]: Using profiles dir at /home/cyril/.dbt
[0m00:58:18.269434 [info ] [MainThread]: Using profiles.yml file at /home/cyril/.dbt/profiles.yml
[0m00:58:18.269842 [info ] [MainThread]: Using dbt_project.yml file at /home/cyril/Documents/vscode_project/dbt_aws/dbt_project.yml
[0m00:58:18.270513 [info ] [MainThread]: adapter type: redshift
[0m00:58:18.271066 [info ] [MainThread]: adapter version: 1.8.0
[0m00:58:18.271508 [info ] [MainThread]: Configuration:
[0m00:58:18.271885 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m00:58:18.272261 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m00:58:18.272655 [info ] [MainThread]: Required dependencies:
[0m00:58:18.273057 [debug] [MainThread]: Executing "git --help"
[0m00:58:18.275680 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m00:58:18.276347 [debug] [MainThread]: STDERR: "b''"
[0m00:58:18.276878 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m00:58:18.277373 [info ] [MainThread]: Connection:
[0m00:58:18.277849 [info ] [MainThread]:   host: default-workgroup.140852924151.us-west-2.redshift-serverless.amazonaws.com
[0m00:58:18.278317 [info ] [MainThread]:   user: dbuser
[0m00:58:18.278765 [info ] [MainThread]:   port: 5439
[0m00:58:18.279204 [info ] [MainThread]:   database: dbt_db
[0m00:58:18.279662 [info ] [MainThread]:   method: database
[0m00:58:18.280085 [info ] [MainThread]:   cluster_id: None
[0m00:58:18.280547 [info ] [MainThread]:   iam_profile: None
[0m00:58:18.281006 [info ] [MainThread]:   schema: public
[0m00:58:18.281463 [info ] [MainThread]:   sslmode: prefer
[0m00:58:18.281876 [info ] [MainThread]:   region: None
[0m00:58:18.282296 [info ] [MainThread]:   sslmode: prefer
[0m00:58:18.282705 [info ] [MainThread]:   region: None
[0m00:58:18.283106 [info ] [MainThread]:   iam_profile: None
[0m00:58:18.283551 [info ] [MainThread]:   autocreate: False
[0m00:58:18.284031 [info ] [MainThread]:   db_groups: []
[0m00:58:18.284485 [info ] [MainThread]:   ra3_node: False
[0m00:58:18.284878 [info ] [MainThread]:   connect_timeout: None
[0m00:58:18.285281 [info ] [MainThread]:   role: None
[0m00:58:18.285679 [info ] [MainThread]:   retries: 1
[0m00:58:18.286072 [info ] [MainThread]:   autocommit: True
[0m00:58:18.286657 [info ] [MainThread]: Registered adapter: redshift=1.8.0
[0m00:58:18.288323 [debug] [MainThread]: Acquiring new redshift connection 'debug'
[0m00:58:18.294171 [debug] [MainThread]: Using redshift connection "debug"
[0m00:58:18.294683 [debug] [MainThread]: On debug: select 1 as id
[0m00:58:18.295099 [debug] [MainThread]: Opening a new connection, currently in state init
[0m00:58:18.300394 [debug] [MainThread]: Redshift adapter: Establishing connection using ssl with `sslmode` set to 'prefer'.To connect without ssl, set `sslmode` to 'disable'.
[0m00:58:18.301778 [debug] [MainThread]: Redshift adapter: Connecting to redshift with username/password based auth...
[0m00:59:16.890138 [error] [MainThread]: Encountered an error:

[0m00:59:16.895492 [error] [MainThread]: Traceback (most recent call last):
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/cli/main.py", line 406, in debug
    results = task.run()
              ^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/task/debug.py", line 150, in run
    connection_status = self.test_connection()
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/task/debug.py", line 471, in test_connection
    connection_result = self.attempt_connection(self.profile)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/task/debug.py", line 449, in attempt_connection
    adapter.debug_query()
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/adapters/redshift/impl.py", line 186, in debug_query
    self.execute("select 1 as id")
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/adapters/base/impl.py", line 350, in execute
    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/adapters/redshift/connections.py", line 346, in execute
    _, cursor = self.add_query(sql, auto_begin)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/adapters/redshift/connections.py", line 372, in add_query
    connection, cursor = super().add_query(
                         ^^^^^^^^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/adapters/sql/connections.py", line 93, in add_query
    cursor = connection.handle.cursor()
             ^^^^^^^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/adapters/contracts/connection.py", line 95, in handle
    self._handle.resolve(self)
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/adapters/contracts/connection.py", line 119, in resolve
    return self.opener(connection)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/adapters/redshift/connections.py", line 327, in open
    open_connection = cls.retry_connection(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/adapters/base/connections.py", line 237, in retry_connection
    connection.handle = connect()
                        ^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/dbt/adapters/redshift/connections.py", line 192, in connect
    c = redshift_connector.connect(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/redshift_connector/__init__.py", line 376, in connect
    return Connection(
           ^^^^^^^^^^^
  File "/home/cyril/Documents/vscode_project/dbt_aws/.venv/lib/python3.12/site-packages/redshift_connector/core.py", line 628, in __init__
    self._usock.connect(hostport)
KeyboardInterrupt

[0m00:59:16.898138 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 58.898182, "process_user_time": 1.489242, "process_kernel_time": 0.259234, "process_mem_max_rss": "100824", "process_out_blocks": "48", "command_success": false, "process_in_blocks": "0"}
[0m00:59:16.899732 [debug] [MainThread]: Command `dbt debug` failed at 00:59:16.899483 after 58.90 seconds
[0m00:59:16.900747 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m00:59:16.902109 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a1029e6ba10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a1029495a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a10294c6d20>]}
[0m00:59:16.903597 [debug] [MainThread]: Flushing usage events
[0m15:59:28.135391 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763c925406b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763c922ae720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763c92540530>]}


============================== 15:59:28.138935 | b28bd7e6-8c7b-4b82-b46b-42fe3c4b5306 ==============================
[0m15:59:28.138935 [info ] [MainThread]: Running with dbt=1.8.2
[0m15:59:28.139615 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/cyril/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs generate', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:59:28.140177 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/cyril/Documents/vscode_project/dbt_aws/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:59:28.141525 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_wall_clock_time": 0.05606009, "process_user_time": 1.222389, "process_kernel_time": 0.144927, "process_mem_max_rss": "85640", "process_in_blocks": "64", "process_out_blocks": "8", "command_success": false}
[0m15:59:28.142257 [debug] [MainThread]: Command `dbt docs generate` failed at 15:59:28.142156 after 0.06 seconds
[0m15:59:28.142702 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763c922ae720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763c92ffd970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x763c92aae540>]}
[0m15:59:28.143133 [debug] [MainThread]: Flushing usage events
